# Generated by Django 5.2.4 on 2025-08-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='image',
        ),
        migrations.AddField(
            model_name='work',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/works/'),
        ),
    ]
